[package]
name = "fo-cli"
description = "File Origin のコマンドラインインターフェース。"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "fo"
path = "src/main.rs"

[dependencies]
fo-core = { workspace = true }
fo-platform = { workspace = true }
fo-store = { workspace = true }
fo-app = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
chrono = { workspace = true }
